### ISSUE TITLE
Documentation for `audio/cfg/*`

### ISSUE THREAD

**Issue by CodeCutterUK** [mjesun/loxberry-music-server-gateway#1]
Is there any documentation/guidance for the payloads involved in `audio/cfg/*`calls/responses?
Specifically `audio/cfg/getmonitorstatus`and `audio/cfg/iamaminiserverdone`

**Comment by mjesun** [comment]
Hi @CodeCutterUK! The `/audio` requests you see are internal requests made from the Miniserver or the UI to the gateway (which acts as a fake Music Server). You don't have to do anything with them :) All the public API is documented in the `README.md` file present in the repository root.

In this particular case you see both erroring because I haven't found what are they used for - but they don't seem to be needed for the correct functioning of the experience.

**Comment by CodeCutterUK** [comment]
@mjesun Thanks for the info.
The underlying challenge I'm facing is that when the MSG is running it invalidates the consistency of the miniserver configuration vs a local file....something that is needed to learn IR commands. Of course the same thing happens when changing a schedule, etc, but that isn't after a few seconds of reprogramming the miniserver.

My first guess was something around these commands, but it could well be something entirely different.

**Comment by CodeCutterUK** [comment]
Issue solved - I needed to ensure the MAC address and options like AirPlay are consistent between the Loxone configuration and the response payload for `audio/cfg/all`
